[tool.poetry]
name = "ansible"
version = "0.1.0"
description = ""
authors = ["Sergey Mizhakov <mizhakov21@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
ansible-runner = "^2.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
