---
- name: Генерация backend файла .env для {{ company_name }}
  hosts: 192.168.0.69
  # hosts: localhost
  become: true
  vars:
    company_name: "{{ company_name }}"
    db_password: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters') }}"
    secret_key: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters') }}"
    wb_api_token: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters') }}"
    tg_bot_token: "6803006551:AAHqrg95sElZp9eZEGXPrddvt_KeYfTnbSA"
    ozon_api_token: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"
    api_hash: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"
    webhook_secret: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"
    minio_access_key: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"
    minio_secret_key: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters') }}"

  tasks:
    - name: Генерация файла .env на основе шаблона
      template:
        src: template/env_backend.j2
        dest: "/srv/site/{{ company_name }}.ismacloud.ru/{{ company_name }}backend/.env"
        # dest: "/srv/ansible/.env"
        mode: '0644'
    # - name: Запуск Docker фронта
    #   community.docker.docker_compose_v2:
    #     project_src: /srv/site/{{ company_name }}.ismacloud.ru/{{ company_name }}frontend
    #     build: true
    #     pull: true
    #     remove_orphans: true
    #     state: present
    #     restarted: true
    # - name: Запуск Docker бэка
    #   community.docker.docker_compose_v2:
    #     project_src: /srv/site/{{ company_name }}.ismacloud.ru/{{ company_name }}backend
    #     build: true
    #     pull: true
    #     remove_orphans: true
    #     state: present
    #     restarted: true